### ISSUE TITLE
Add Sales GUI

### ISSUE THREAD

**Issue by kunaldhanawade** [kunaldhanawade/inventory-mamagement-system-in-python#11]
I want people from the open-source community to collab with me in this project.

Please add Sales GUI, wherein the admin can VIEW bills.

**Comment by rahulbharaskar** [comment]
Hi, Kunal I am ready to contribute to your project. I can Build GUI for sales section.

**Comment by SanjayPatra83** [comment]
> Hi, Kunal I am ready to contribute to your project. I can Build GUI for sales section.

Hi, Kunal I am ready to contribute to your project. I can Build GUI for employee frame.

You have not added function to a button

**Comment by SanjayPatra83** [comment]
Hi, Kunal I am ready to contribute to your project. I will add the function for the button
