### ISSUE TITLE
Adding Product GUI

### ISSUE THREAD

**Issue by kunaldhanawade** [kunaldhanawade/inventory-mamagement-system-in-python#8]
I want people from the open-source community to collab with me in this project.

Please add Product GUI, wherein the admin can ADD a Product, UPDATE Product Details, DELETE a Product, SEARCH a Product and SHOW Products in a tabular form

**Comment by Vikrant-14** [comment]
Hello Kunal, I am willing to contribute in your project. So I am ready to build a GUI Framework for Product window.

**Comment by janhavijain0810** [comment]
> Hello Kunal, I am willing to contribute in your project. So I am ready to build a GUI Framework for Product window.
You have not added functions for buttons

**Comment by janhavijain0810** [comment]
Hi, Kunal I am ready to contribute to your project. I will add functions for buttons.
